### ISSUE TITLE
[Suggestion] Item blacklist

### ISSUE THREAD

**Issue by Tsyklop** [Epoxide-MC/Enchanting-Plus#12]
Add the black list of items that can not be enchanted.

**Comment by darkhax** [comment]
I am not sure what you mean by this suggestions. There is already an Item blacklist, which prevents an Item from being used. This blacklist can be accessed using IMC.

**Comment by Tsyklop** [comment]
@darkhax I mean that it would be possible to remove the ability to enchant, for example, and the drill of any mod.

**Comment by darkhax** [comment]
Yes, this is already possible through IMC, which can be accessed through DynIMC, ModTweaker or any other mod, although that requires code knowledge. Are you asking for the ability to add entries from a configuration file?

**Comment by Tsyklop** [comment]
@darkhax yes.

**Comment by darkhax** [comment]
I have added in support for the item/block blacklisting. It will now generate in your configuration file. Access to the enchantment blacklist will be soon added. It's important for everyone to keep in mind that this should not be used as the main way to patch bugs related to various items and enchantments. If a specific item or enchantment should be blacklisted for the sake of patching a bug, it should be reported so we can add a special case.
