### ISSUE TITLE
The Advanced Enchantment Table doesn't have a recipe

### ISSUE THREAD

**Issue by Hund** [Epoxide-MC/Enchanting-Plus#14]
I'm running my own custom modpack using:

* Enchanting Plus 4.0.0.54 (RC1)
* Bookshelf 1.0.3.138
* Forge 10.13.4.1558

The Advanced Enchantment Table doesn't have a recipe. I had to switch to creative mode to cheat in the table.

**Comment by darkhax** [comment]
The table is obtained by right clicking on the vanilla table with the enchantment table upgrade. 
![image](https://cloud.githubusercontent.com/assets/2250798/11618935/b1385e08-9c5e-11e5-9a07-cd9ff987481c.png)

That being said, it wouldn't hurt to add back the old recipe.

**Comment by Hund** [comment]
Oh! Is this also documented somewhere? As I said in the previous comment, I
though I have read everything.

**Comment by darkhax** [comment]
This specific recipe is documented on the [CurseForge](http://www.curse.com/mc-mods/minecraft/enchanting-plus) page. Where did you download this version of the mod from?

**Comment by darkhax** [comment]
This latest change adds two new recipes. They will show up in RC2.

![shapeless](https://cloud.githubusercontent.com/assets/2250798/11619342/169b71f4-9c64-11e5-8646-e07c8c23de68.PNG)

![shaped](https://cloud.githubusercontent.com/assets/2250798/11619344/195afec8-9c64-11e5-9909-7e1fa30f54df.PNG)

**Comment by Hund** [comment]
Great! :)

**Comment by Hund** [comment]
I missed your previous reply. I download all my mods from Curseforge and it was there I saw the recipe as well. But I didn't see any documentation about the two things I had problems with, that's why I assumed it was bugs and not features.
