### ISSUE TITLE
[Enhancement] Add 1.8.9 support too

### ISSUE THREAD

**Issue by hron84** [Epoxide-MC/Enchanting-Plus#22]
I saw E+ 3 has an 1.8 port. Can you update this to 1.8.9?

**Comment by hron84** [comment]
@darkhax Can you explain me why invalid and wontfix? Curse does not list E+ downloads for 1.8.9 only for 1.8. Supporting 1.8 is not implicitly means you are supporting 1.8.9 too, a lot of mods does not compatible with 1.8.9 even if they supporting previous 1.8 versions (1.8.8 or 1.8.0 for example). Please, if you can, explain this for me.

**Comment by darkhax** [comment]
The current 1.8 alpha version is not supported by the current development team. The current 1.7.10 version is ahead of the 1.8 alpha in terms of content and bug fixes. As far as the current dev team is concerned, we are not supporting 1.8 at all right now.

**Comment by hron84** [comment]
@darkhax I see. Sorry, but this was not clear from a "invalid, wontfix" tag. I really appreciate your detailed answer. Thanks anyway, and keep up this awesome work. I'm really excited about E+ 4 new features.

**Comment by miiichael** [comment]
Ah, so to be clear, does this mean there are currently no plans for any version of E+ to support 1.8.x (or 1.9.x for that matter...)?

**Comment by darkhax** [comment]
@miiichael They will come eventually.
