### ISSUE TITLE
Console Spam and Unplayable

### ISSUE THREAD

**Issue by ReportBot9009** [Epoxide-MC/Enchanting-Plus#9]
Hey Darkhax!

Firstly, thank you so incredibly much for taking the reigns of this mod. Not five minutes ago I noticed a new download for it and I was so excited! Thank you thank you!

Now with the problem:

I loaded up my modded Minecraft and immediately noticed the 0 FPS and game spike every 3 seconds. The game would freeze for 3 seconds then let up. This went on ad infinitum.

There was no crash however, but the MultiMC console log spammed this: [16:19:48] [Client thread/WARN] [Bookshelf]: The ASM has not been initialized, there is an error with your setup!

Not sure what it is, but it is.

Do you need a modlist or anything?

Thanks again

**Comment by ReportBot9009** [comment]
Sorry, maybe this needs to go into Bookshelf Git. I'll copy and post over there and you can close this one?

**Comment by darkhax** [comment]
Yes, this is a bookshelf issue. I have already posted on your other issue. https://github.com/Darkhax-Minecraft/Bookshelf/issues/18
